languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source UI Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /assets/brand/coreui-social.jpg
  social_logo_path:     /assets/brand/coreui-social-logo.png

  current_version:      "4.2.0"
  current_version_pro:  "4.5.0"
  current_ruby_version: "4.2.0"
  docs_version:         "4.1"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  opencollective:       "coreui"
  community:            "https://github.com/coreui/coreui/discussions"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.2.0.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.2.0/coreui-4.2.0-dist.zip"
    source_pro:         "https://github.com/coreui/coreui-pro/archive/v4.5.0.zip"
    dist_pro:           "https://github.com/coreui/coreui-pro/releases/download/v4.5.0/coreui-4.5.0-dist.zip"

  download_template:
    website:            "https://coreui.io/product/free-bootstrap-admin-template/"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:                 "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.0/dist/css/coreui.min.css"
    css_hash:            "sha384-UkVD+zxJKGsZP3s/JuRzapi4dQrDDuEf/kHphzg8P3v8wuQ6m9RLjTkPGeFcglQU"
    css_rtl:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.0/dist/css/coreui.rtl.min.css"
    css_rtl_hash:        "sha384-7W1eMOzj3wRp1Oat/SJe+uPZ3lBB5YWlrjI9zeLbto2KkseMeJKSGAs4844qZPjz"
    js:                  "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.0/dist/js/coreui.min.js"
    js_hash:             "sha384-2hww80ziDjQXYpFulPf5tfdCCXLTxn70HdSwL9MfeEvpS0kjfHd1iaBRsLpnuaSC"
    js_bundle:           "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.0/dist/js/coreui.bundle.min.js"
    js_bundle_hash:      "sha384-n0qOYeB4ohUPebL1M9qb/hfYkTp4lvnZM6U6phkRofqsMzK29IdkBJPegsyfj/r4"
    popper:              "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    popper_hash:         " sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
    css_pro:             "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/css/coreui.min.css"
    css_pro_hash:        "sha384-0XB01Q5KvRtVARnxs/Bf7U8G3YGyhmoSv19lcnXDzQ1cp4aautcSK4P5OvCthQj0"
    css_pro_rtl:         "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/css/coreui.rtl.min.css"
    css_pro_rtl_hash:    "sha384-Z7kTvRzCOJTQ0hPBhyTW1VzUE2EDlUXXHlFVVsi/lmJI8oSSj8S8v9F3RoY0FSm+"
    js_pro:              "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/js/coreui.min.js"
    js_pro_hash:         "sha384-sgL2dnscCq1mBD/ZiUhyxMZT41vg+M6a/XWTCJsjBTaqZ1uWGF+ZwD8YIWstvXeT"
    js_pro_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/js/coreui.bundle.min.js"
    js_pro_bundle_hash:  "sha384-DIs4n/vvjSI9MoFe804AsdvYdssJcpUht3fJZ2a+lc5h5kY3dQVrgOOB3hSbAN3r"

  anchors:
    min: 2
    max: 5
