languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/4.6/"
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source UI Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /assets/brand/coreui-social.jpg
  social_logo_path:     /assets/brand/coreui-social-logo.png

  current_version:      "4.2.0"
  current_version_pro:  "4.5.0"
  current_ruby_version: "4.2.0"
  docs_version:         "4.1"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  opencollective:       "coreui"
  community:            "https://github.com/coreui/coreui/discussions"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.3.0-alpha.0.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.3.0-alpha.0/coreui-4.3.0-alpha.0-dist.zip"
    source_pro:         "https://github.com/coreui/coreui-pro/archive/v4.5.0.zip"
    dist_pro:           "https://github.com/coreui/coreui-pro/releases/download/v4.5.0/coreui-4.5.0-dist.zip"

  download_template:
    website:            "https://coreui.io/product/free-bootstrap-admin-template/"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.3.0-alpha.0/dist/css/coreui.min.css"
    css_hash:        "sha384-MfiafU8FNerl5tlunB5f6iMEGJ3KrqJga0zkA9OPWzKR8W6UenHgZI4SdfNjn8zL"
    css_rtl:         "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.3.0-alpha.0/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-hPTUjiP+oWx8ltR+9wiZKFGf3BU0nuOsXJmrsgTfZQowgW9k0wtjgDJVCDtHOoUl"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.3.0-alpha.0/dist/js/coreui.min.js"
    js_hash:         "sha384-SNBINhaW16aFRorhuZgq6f2m9//dBqdXtCIYH828JLS9m/DkGi9K3xoQzGkZeWxb"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.3.0-alpha.0/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-4rXehlv2uFB3REIcn+690wKP8X6f8/p7Y+fr+C/N1ZTZ7FuSBdjRKGeSQQgBy7zO"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    popper_hash:      "sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
    css_pro:             "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/css/coreui.min.css"
    css_pro_hash:        "sha384-0XB01Q5KvRtVARnxs/Bf7U8G3YGyhmoSv19lcnXDzQ1cp4aautcSK4P5OvCthQj0"
    css_pro_rtl:         "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/css/coreui.rtl.min.css"
    css_pro_rtl_hash:    "sha384-Z7kTvRzCOJTQ0hPBhyTW1VzUE2EDlUXXHlFVVsi/lmJI8oSSj8S8v9F3RoY0FSm+"
    js_pro:              "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/js/coreui.min.js"
    js_pro_hash:         "sha384-sgL2dnscCq1mBD/ZiUhyxMZT41vg+M6a/XWTCJsjBTaqZ1uWGF+ZwD8YIWstvXeT"
    js_pro_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.5.0/dist/js/coreui.bundle.min.js"
    js_pro_bundle_hash:  "sha384-DIs4n/vvjSI9MoFe804AsdvYdssJcpUht3fJZ2a+lc5h5kY3dQVrgOOB3hSbAN3r"

  anchors:
    min: 2
    max: 5
